

SUBDIRS += walking_1s

include Makefile.inc

# The plan is to make this operate like a "subdirs" BSD makefile;
# the subdirectories will be listed and then the makefile will recursively call
# "make all" in each of them.

