
OBJS+=test.o
RECOMPILE_DIRS += $(H2DIR)/kernel/data/intconfig
RECOMPILE_SRCS_PREFS += intconfig

EXTRA_CFLAGS += -DTESTING
EXTRA_ASFLAGS += -DTESTING

EXEC=test.elf
STANDALONE=1
include Makefile.inc
OSLIB=
