/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#ifndef H2_PREFETCH_H
#define H2_PREFETCH_H

#define H2_PREFETCH_L1I_OFF 0
#define H2_PREFETCH_L1I_LOW 1
#define H2_PREFETCH_L1I_MED 2
#define H2_PREFETCH_L1I_HIGH H2_PREFETCH_L1I_MED
#define H2_PREFETCH_L1I H2_PREFETCH_L1I_HIGH

#define H2_PREFETCH_L1D_OFF 0
#define H2_PREFETCH_L1D_LOW H2_PREFETCH_L1D_OFF
#define H2_PREFETCH_L1D_MED H2_PREFETCH_L1D_LOW
#define H2_PREFETCH_L1D_HIGH H2_PREFETCH_L1D_MED
#define H2_PREFETCH_L1D H2_PREFETCH_L1D_HIGH

#define H2_PREFETCH_L2I_OFF 0x00
#define H2_PREFETCH_L2I_LOW 0x08
#define H2_PREFETCH_L2I_MED 0x10
#define H2_PREFETCH_L2I_HIGH 0x18
#define H2_PREFETCH_L2I H2_PREFETCH_L2I_HIGH

#define H2_PREFETCH_L2D_OFF 0x00
#define H2_PREFETCH_L2D_LOW H2_PREFETCH_L2D_OFF
#define H2_PREFETCH_L2D_MED H2_PREFETCH_L2D_LOW
#define H2_PREFETCH_L2D_HIGH H2_PREFETCH_L2D_MED
#define H2_PREFETCH_L2D H2_PREFETCH_L2D_HIGH

#define H2_PREFETCH_I (H2_PREFETCH_L1I | H2_PREFETCH_L2I)
#define H2_PREFETCH_D (H2_PREFETCH_L1D | H2_PREFETCH_L2D)
#define H2_PREFETCH_SW (0)

void h2_set_prefetch(unsigned int settings);

#endif

