STANDALONE=1

OBJS+=test.o
EXEC=test.elf
PYTHON_GENERATOR_SCRIPT=scenarios.py
PYTHON_GENERATED_FILES=scenarios.h

# Include the include makefile.
include Makefile.inc

# Empty out the OSLIB variable.
OSLIB=
