BOOT=1
OBJS = $(patsubst %.c, %.o, $(wildcard *.c))
OBJS += $(patsubst %.cc, %.o, $(wildcard *.cc))
EXEC=test.elf
ULIMIT := 240

include ${H2DIR}/scripts/Makefile.inc.test
-include make.inc

LDFLAGS += $(LDFLAGS_EXTRA)
