/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#ifndef H2_COMMON_HWCONFIG_H
#define H2_COMMON_HWCONFIG_H 1

#include <h2_common_defs.h>

typedef enum {
	HWCONFIG_L2CACHE,
	HWCONFIG_PARTITIONS,
	HWCONFIG_PREFETCH,
	HWCONFIG_EXTBITS,
	HWCONFIG_VLENGTH,
	HWCONFIG_EXTPOWER,
	HWCONFIG_GETL2REG,
	HWCONFIG_SETL2REG,
	HWCONFIG_L2LOCKA,
	HWCONFIG_L2UNLOCK,
	HWCONFIG_HWINTOP,
	HWCONFIG_GETCLADEREG,
	HWCONFIG_SETCLADEREG,
	HWCONFIG_HWTHREADS_NUM,
	HWCONFIG_HWTHREADS_MASK,
	HWCONFIG_ECC,
	HWCONFIG_HMXBITS,
	HWCONFIG_GETDMACFG,
	HWCONFIG_SETDMACFG,
	HWCONFIG_L2GCLEAN,
	HWCONFIG_GETSTRIDEPREFETCHERREG,
	HWCONFIG_SETSTRIDEPREFETCHERREG,
	HWCONFIG_SETHMXPOWERONSTARTADDR,
	HWCONFIG_SETHMXPOWEROFFSTARTADDR,
	HWCONFIG_GPIOTOGGLE,
	HWCONFIG_SETGPIOADDR,
	HWCONFIG_L2CP,
	HWCONFIG_GETECCREG,
	HWCONFIG_GETVWCTRL,
	HWCONFIG_SETVWCTRL,
	HWCONFIG_GET_DPM_VOLTLMTMGMT_REG,
	HWCONFIG_SET_DPM_VOLTLMTMGMT_REG,	
	HWCONFIG_HLXBITS,
	HWCONFIG_HLXLENGTH,
	HWCONFIG_MAX
} hwconfig_type_t;

enum {
HWCONFIG_PREFETCH_HF_I,
HWCONFIG_PREFETCH_HF_D,
HWCONFIG_PREFETCH_SF_D,
HWCONFIG_PREFETCH_HF_I_L2,
HWCONFIG_PREFETCH_SF_D_L2
};

#define ECCREGS_NREGS 8
#define ECCREGS_STRIDE 0x100
#define ECCREGS_MAX (ECCREGS_STRIDE * (ECCREGS_NREGS - 1))
#define ECCREGS_ENABLE 0xa
#define ECCREGS_DISABLE 0x5
#define ECCREGS_BITS 4

/** 
Constants for choosing a cache to change partitioning on
*/
enum {
	HWCONFIG_PARTITION_D,	/**< Select the Data Cache */
	HWCONFIG_PARTITION_I,	/**< Select the Instruction Cache */
	HWCONFIG_PARTITION_L2	/**< Select the L2 Cache */
};

/** 
Constants for choosing a partitioning type
*/
enum {
	HWCONFIG_PARTITION_SHARED,	/**< Select fully shared */
	HWCONFIG_PARTITION_AUX_HALF,	/**< Select Half and Half partition */
	HWCONFIG_PARTITION_AUX_QUARTER,	/**< Select 1/4 and 3/4 partition */
	HWCONFIG_PARTITION_AUX_EIGHTH	/**< Select 1/8 and 7/8 partition */
};

/**
Constants for partition by thread
*/
enum {
	HWCONFIG_L2CP_CCCC, /**< Use CCCC page-attribute bits */
	HWCONFIG_L2CP_MAIN, /**< Use main partition */
	HWCONFIG_L2CP_AUX,  /**< Use aux partition */
	HWCONFIG_L2CP_MIN /**< Use minimum cache space */
};

/** 
Constants for choosing a hardware interrupt operation
*/
enum {
	HWCONFIG_HWINTOP_ENABLE,
	HWCONFIG_HWINTOP_DISABLE,
	HWCONFIG_HWINTOP_RAISE,
	HWCONFIG_HWINTOP_XXX_LAST
};

#endif
