/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

/* defines only */

#ifndef H2_COMMON_DEFS_H
#define H2_COMMON_DEFS_H 1

#if ARCHV >= 60
#define HAVE_EXTENSIONS 1
#endif

#ifndef MAX_HTHREADS
#if ARCHV <= 3
#define MAX_HTHREADS 6
#elif ARCHV == 4
#define MAX_HTHREADS 3
#elif ARCHV == 5
#define MAX_HTHREADS 6
#elif ARCHV == 60
#define MAX_HTHREADS 4
#endif
#endif

#define SYSCFG_M_BIT 0
#define SYSCFG_M_LEN 1
#define SYSCFG_M (((0x1 << SYSCFG_M_LEN) - 1) << SYSCFG_M_BIT)
#define SYSCFG_I_BIT 1
#define SYSCFG_I_LEN 1
#define SYSCFG_I (((0x1 << SYSCFG_I_LEN) - 1) << SYSCFG_I_BIT)
#define SYSCFG_D_BIT 2
#define SYSCFG_D_LEN 1
#define SYSCFG_D (((0x1 << SYSCFG_D_LEN) - 1) << SYSCFG_D_BIT)
#define SYSCFG_T_BIT 3
#define SYSCFG_T_LEN 1
#define SYSCFG_T (((0x1 << SYSCFG_T_LEN) - 1) << SYSCFG_T_BIT)
#define SYSCFG_G_BIT 4
#define SYSCFG_G_LEN 1
#define SYSCFG_G (((0x1 << SYSCFG_G_LEN) - 1) << SYSCFG_G_BIT)
#define SYSCFG_R_BIT 5
#define SYSCFG_R_LEN 1
#define SYSCFG_R (((0x1 << SYSCFG_R_LEN) - 1) << SYSCFG_R_BIT)
#define SYSCFG_C_BIT 6
#define SYSCFG_C_LEN 1
#define SYSCFG_C (((0x1 << SYSCFG_C_LEN) - 1) << SYSCFG_C_BIT)

#ifdef HAVE_EXTENSIONS
#define SYSCFG_V2X_BIT 7
#define SYSCFG_V2X_LEN 1
#define SYSCFG_V2X (((0x1 << SYSCFG_V2X_LEN) - 1) << SYSCFG_V2X_BIT)
#define V2X_LENGTH 7
#endif

#define SYSCFG_IDA_BIT 8
#define SYSCFG_IDA_LEN 1
#define SYSCFG_IDA (((0x1 << SYSCFG_IDA_LEN) - 1) << SYSCFG_IDA_BIT)
#define SYSCFG_PM_BIT 9
#define SYSCFG_PM_LEN 1
#define SYSCFG_PM (((0x1 << SYSCFG_PM_LEN) - 1) << SYSCFG_PM_BIT)
#define SYSCFG_TE_LEN 1
#define SYSCFG_TE_BIT 10
#define SYSCFG_TE (((0x1 << SYSCFG_TE_BIT) - 1) << SYSCFG_TE_BIT)
#define SYSCFG_TL_BIT 11
#define SYSCFG_TL_LEN 1
#define SYSCFG_TL (((0x1 << SYSCFG_TL_LEN) - 1) << SYSCFG_TL_BIT)
#define SYSCFG_KL_BIT 12
#define SYSCFG_KL_LEN 1
#define SYSCFG_KL (((0x1 << SYSCFG_KL_LEN) - 1) << SYSCFG_KL_BIT)
#define SYSCFG_BQ_BIT 13
#define SYSCFG_BQ_LEN 1
#define SYSCFG_BQ (((0x1 << SYSCFG_BQ_LEN) - 1) << SYSCFG_BQ_BIT)
#define SYSCFG_PRIO_BIT 14
#define SYSCFG_PRIO_LEN 1
#define SYSCFG_PRIO (((0x1 << SYSCFG_PRIO_LEN) - 1) << SYSCFG_PRIO_BIT)
#define SYSCFG_DMT_BIT 15
#define SYSCFG_DMT_LEN 1
#define SYSCFG_DMT (((0x1 << SYSCFG_DMT_LEN) - 1) << SYSCFG_DMT_BIT)

#define SYSCFG_L2CFG_BITS 16
#define SYSCFG_L2CFG_LEN 3
#define SYSCFG_L2CFG (((0x1 << SYSCFG_L2CFG_LEN) - 1) << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_0K (0 << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_64K (1 << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_128K (2 << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_256K (3 << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_512K (4 << SYSCFG_L2CFG_BITS)
#define SYSCFG_L2CFG_1024K (5 << SYSCFG_L2CFG_BITS)

#define SYSCFG_ITCM_BIT 19
#define SYSCFG_ITCM_LEN 1
#define SYSCFG_ITCM (((0x1 << SYSCFG_ITCM_LEN) - 1) << SYSCFG_ITCM_BIT)

#define SYSCFG_L2NWA_BIT 21
#define SYSCFG_L2NWA_LEN 1
#define SYSCFG_L2NWA (((0x1 << SYSCFG_L2NWA_LEN) - 1) << SYSCFG_L2NWA_BIT)
#define SYSCFG_L2NRA_BIT 22
#define SYSCFG_L2NRA_LEN 1
#define SYSCFG_L2NRA (((0x1 << SYSCFG_L2NRA_LEN) - 1) << SYSCFG_L2NRA_BIT)

#define SYSCFG_L2WB_BIT 23
#define SYSCFG_L2WB_LEN 1
#define SYSCFG_L2WB (((0x1 << SYSCFG_L2WB_LEN) - 1) << SYSCFG_L2WB_BIT)
#define SYSCFG_L2P_BIT 24
#define SYSCFG_L2P_LEN 1
#define SYSCFG_L2P (((0x1 << SYSCFG_L2P_LEN) - 1) << SYSCFG_L2P_BIT)
#define SYSCFG_L1DP_BITS 25
#define SYSCFG_L1DP_LEN 2
#define SYSCFG_L1DP (((0x1 << SYSCFG_L1DP_LEN) - 1) << SYSCFG_L1DP_BIT)
#define SYSCFG_L1IP_BITS 27
#define SYSCFG_L1IP_LEN 2
#define SYSCFG_L1IP (((0x1 << SYSCFG_L1IP_LEN) - 1) << SYSCFG_L1IP_BIT)
#define SYSCFG_L2PART_BITS 29
#define SYSCFG_L2PART_LEN 2
#define SYSCFG_L2PART (((0x1 << SYSCFG_L2PART_LEN) - 1) << SYSCFG_L2PART_BIT)

#endif
